version: '3.1'

services:

  db:
    image: mariadb:10
    restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: cashbox-dev
      MARIADB_USER: cashbox
      MARIADB_PASSWORD: cashbox
    ports:
      - "3307:3306"
    volumes:
      - ./init:/docker-entrypoint-initdb.d
