name: Frontend Tests

on:
  pull_request:
    types: [opened, synchronize]
  workflow_call:
    inputs:
      ref:
        type: string
        description: The branch, tag or SHA to deploy
        required: true

jobs:
  frontend_test:
    name: Frontend Tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend

    strategy:
      matrix:
        node-version: [ 18.x ]

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        if: inputs.ref
        with:
          ref: ${{ inputs.ref }}
      - name: Checkout
        uses: actions/checkout@v3
        if: !inputs.ref

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Get npm cache directory
        id: npm-cache-dir
        run: |
          echo "::set-output name=dir::$(npm config get cache)"
      - uses: actions/cache@v3
        id: npm-cache
        with:
          path: ${{ steps.npm-cache-dir.outputs.dir }}
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - run: npm ci
      - run: npm run test:ci
      - run: npm run lint
      - name: Archive code coverage result
        if: success()
        uses: actions/upload-artifact@v1
        with:
          name: deploy_coverage
          path: frontend/coverage
      - name: Upload code coverage
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./frontend/coverage/cashbox-frontend/lcov.info
          fail_ci_if_error: true
