name: Lint PR title

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize

jobs:
  title-lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install Dependencies
        run: npm install @commitlint/config-conventional
      - uses: JulienKode/pull-request-name-linter-action@v0.5.0
