name: Lint PR title

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize

jobs:
  title-lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: dreampulse/action-commitlint-pull-request-title@2b9c111eb0916d6da6318634db6a1d595edefa83
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          commitlintConfigFile: commitlint.config.js
